"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";

type ScriptRec = { scriptNumber: string; dispenseDate: string; patient: string; medicine: string; quantity: string; medicare?: string };
type Scan = { value: string; savedAt: string; status: "matched" | "unmatched"; record?: ScriptRec };
type PrescriptionEntry = { id: string; savedAt: string; source: "manual" | "fred-search" | "scanner"; scriptNumber?: string; patient: string; address?: string; date: string; medicine: string; medicare: string; quantity?: string; repeats?: string; directions?: string; itemIndex?: number };
type Batch = { fileName: string; uploadedAt: string; from: string; to: string; imported: number; updated: number; total: number };
type RawRow = Record<string, string>;
type RxManual = { patient: string; date: string; medicine: string; medicare: string };
type TableMode = "matched" | "unmatchedLabels" | "unmatchedPrescriptions";
type ScannerControls = { stop: () => void };
type ReviewRow = Record<string, string>;
type RecentItem = { kind: "Label" | "Prescription"; title: string; subtitle: string; time: string };
type AiMedicine = { medicine?: string; labelNumber?: string; quantity?: string; repeats?: string; directions?: string; confidence?: number };

const DB = "pharmacy-verification-db";
const SCRIPT_KEY = "fred-master-scripts-v3";
const SCAN_KEY = "fred-label-scans-v3";
const PRESCRIPTION_KEY = "prescription-entries-v2";
const BATCH_KEY = "fred-upload-batches-v3";
const SCRIPT_COLS = ["script number", "script no", "rx", "rx no", "prescription no", "prescription number", "label", "label no"];
const DATE_COLS = ["dispense date", "dispensed date", "date dispensed", "script date", "prescribed date", "date"];
const LAST_COLS = ["patient last name", "last name", "surname"];
const FIRST_COLS = ["patient first name", "first name", "given name"];
const PATIENT_COLS = ["patient", "patient name", "name", "customer", "client"];
const MED_COLS = ["drug description", "drug", "medicine", "medication", "brand name", "generic name", "description", "product"];
const QTY_COLS = ["quantity", "qty", "qty supplied", "quantity supplied"];
const MEDICARE_COLS = ["patient medicare", "medicare", "medicare number", "medicare no"];

const norm = (v: unknown) => String(v ?? "").toLowerCase().replace(/[^a-z0-9]+/gi, "").trim();
const dig = (v: unknown) => String(v ?? "").replace(/\D/g, "");
const cleanLabel = (v: unknown) => String(v ?? "").trim().replace(/^[\s(]+/g, "").trim();
const id = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const sleep = (ms: number) => new Promise((resolve) => window.setTimeout(resolve, ms));
const isLikelyAddress = (v: string) => /\b(st|street|rd|road|ave|avenue|dr|drive|ct|court|unit|apt|darwin|nt|qld|nsw|vic|wa|sa|tas|act)\b/i.test(v) || /\d+\s+[a-z]/i.test(v);

function openDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const req = indexedDB.open(DB, 1); req.onupgradeneeded = () => req.result.createObjectStore("kv"); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); }
async function idbGet<T>(key: string, fallback: T): Promise<T> { const db = await openDb(); return new Promise((resolve) => { const req = db.transaction("kv", "readonly").objectStore("kv").get(key); req.onsuccess = () => resolve((req.result as T) ?? fallback); req.onerror = () => resolve(fallback); }); }
async function idbSet<T>(key: string, value: T) { const db = await openDb(); return new Promise<void>((resolve, reject) => { const req = db.transaction("kv", "readwrite").objectStore("kv").put(value, key); req.onsuccess = () => resolve(); req.onerror = () => reject(req.error); }); }
async function idbDel(key: string) { const db = await openDb(); return new Promise<void>((resolve) => { const req = db.transaction("kv", "readwrite").objectStore("kv").delete(key); req.onsuccess = () => resolve(); req.onerror = () => resolve(); }); }
function pick(row: RawRow, keys: string[]) { const entries = Object.entries(row); const exact = entries.find(([k]) => keys.includes(k.toLowerCase().trim())); if (exact?.[1]) return String(exact[1]).trim(); const fuzzy = entries.find(([k]) => keys.some((key) => k.toLowerCase().trim().includes(key))); return String(fuzzy?.[1] ?? "").trim(); }
function auDate(raw: string) { if (!raw) return ""; const m = String(raw).match(/(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})/); if (m) return `${m[1].padStart(2, "0")}/${m[2].padStart(2, "0")}/${m[3].length === 2 ? `20${m[3]}` : m[3]}`; const d = new Date(raw); return Number.isNaN(d.getTime()) ? raw : new Intl.DateTimeFormat("en-AU").format(d); }
function dateValue(raw: string) { const m = String(raw).match(/(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})/); if (m) return new Date(Number(m[3].length === 2 ? `20${m[3]}` : m[3]), Number(m[2]) - 1, Number(m[1])).getTime(); const d = new Date(raw); return Number.isNaN(d.getTime()) ? 0 : d.getTime(); }
function findHeaderIndex(rows: unknown[][]) { const idx = rows.findIndex((row) => { const text = row.map((c) => String(c ?? "").toLowerCase()).join(" | "); return text.includes("script number") && (text.includes("patient") || text.includes("drug description")); }); return idx >= 0 ? idx : 0; }
function rowsToScripts(rows: RawRow[]) { return rows.map((row) => { const first = pick(row, FIRST_COLS); const last = pick(row, LAST_COLS); return { scriptNumber: pick(row, SCRIPT_COLS), dispenseDate: pick(row, DATE_COLS), patient: [first, last].filter(Boolean).join(" ") || pick(row, PATIENT_COLS), medicine: pick(row, MED_COLS), quantity: pick(row, QTY_COLS), medicare: pick(row, MEDICARE_COLS) } satisfies ScriptRec; }).filter((r) => r.scriptNumber || r.patient || r.medicine); }
function splitCsvLine(line: string, delim: string) { const out: string[] = []; let cur = ""; let quote = false; for (let i = 0; i < line.length; i += 1) { const c = line[i]; if (c === '"' && quote && line[i + 1] === '"') { cur += '"'; i += 1; } else if (c === '"') quote = !quote; else if (c === delim && !quote) { out.push(cur.trim()); cur = ""; } else cur += c; } out.push(cur.trim()); return out; }
function parseText(text: string) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).map((l) => l.trim()).filter(Boolean); if (lines.length < 2) return []; const delim = [",", "\t", ";", "|"].reduce((best, d) => lines[0].split(d).length > lines[0].split(best).length ? d : best, ","); const headers = splitCsvLine(lines[0], delim); const rows = lines.slice(1).map((line) => { const cells = splitCsvLine(line, delim); return headers.reduce<RawRow>((row, h, i) => { row[h || `Column ${i + 1}`] = cells[i] ?? ""; return row; }, {}); }); return rowsToScripts(rows); }
async function parseFredFile(file: File) { const ext = file.name.split(".").pop()?.toLowerCase(); if (ext === "xlsx" || ext === "xls") { const wb = XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: false }); const sheet = wb.Sheets[wb.SheetNames[0]]; const matrix = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: "", raw: false }); const headerIndex = findHeaderIndex(matrix); const headers = matrix[headerIndex].map((h, i) => String(h || `Column ${i + 1}`).trim()); const rows = matrix.slice(headerIndex + 1).map((line) => headers.reduce<RawRow>((row, h, i) => { row[h] = String(line[i] ?? "").trim(); return row; }, {})); return rowsToScripts(rows); } return parseText(await file.text()); }
function rangeLabel(records: ScriptRec[]) { const dates = records.map((r) => r.dispenseDate).filter(Boolean).sort((a, b) => dateValue(a) - dateValue(b)); return { from: auDate(dates[0] || ""), to: auDate(dates[dates.length - 1] || "") }; }
function findScript(records: ScriptRec[], value: string) { const c = norm(value); const d = dig(value); if (!c && !d) return undefined; return records.find((r) => { const sd = dig(r.scriptNumber); return norm(r.scriptNumber) === c || Boolean(d && sd && (sd === d || d.includes(sd) || sd.includes(d))); }); }
function medLooksSame(a = "", b = "") { const na = norm(a), nb = norm(b); return !na || !nb || na.includes(nb) || nb.includes(na); }
function csvCell(value: unknown) { const text = String(value ?? ""); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
function downloadCsv(fileName: string, rows: ReviewRow[]) { if (rows.length === 0) return; const headers = Object.keys(rows[0]); const csv = [headers.join(","), ...rows.map((row) => headers.map((header) => csvCell(row[header])).join(","))].join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url); }
const fmt = (v: string) => new Intl.DateTimeFormat("en-AU", { dateStyle: "short", timeStyle: "short" }).format(new Date(v));

export default function Home() {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const zxingControlsRef = useRef<ScannerControls | null>(null);
  const [scripts, setScripts] = useState<ScriptRec[]>([]);
  const [scans, setScans] = useState<Scan[]>([]);
  const [prescriptions, setPrescriptions] = useState<PrescriptionEntry[]>([]);
  const [batches, setBatches] = useState<Batch[]>([]);
  const [manual, setManual] = useState("");
  const [detected, setDetected] = useState("");
  const [cameraOn, setCameraOn] = useState(false);
  const [scannerBusy, setScannerBusy] = useState(false);
  const [last, setLast] = useState<Scan | null>(null);
  const [message, setMessage] = useState("Start scanner. Barcode = label. No barcode = prescription AI scan.");
  const [toast, setToast] = useState("");
  const [flash, setFlash] = useState(false);
  const [uploadState, setUploadState] = useState({ active: false, percent: 0, label: "" });
  const [rxManual, setRxManual] = useState<RxManual>({ patient: "", date: "", medicine: "", medicare: "" });
  const [tableMode, setTableMode] = useState<TableMode>("matched");

  function notify(text: string) { setToast(text); setMessage(text); setFlash(true); window.setTimeout(() => setFlash(false), 850); window.setTimeout(() => setToast(""), 2600); }

  useEffect(() => { void (async () => { const s = await idbGet<ScriptRec[]>(SCRIPT_KEY, []); const sc = await idbGet<Scan[]>(SCAN_KEY, []); const p = await idbGet<PrescriptionEntry[]>(PRESCRIPTION_KEY, []); const b = await idbGet<Batch[]>(BATCH_KEY, []); setScripts(s); setScans(sc); setPrescriptions(p); setBatches(b); setLast(sc[0] ?? null); })(); }, []);
  useEffect(() => { void idbSet(SCRIPT_KEY, scripts); }, [scripts]);
  useEffect(() => { void idbSet(SCAN_KEY, scans); }, [scans]);
  useEffect(() => { void idbSet(PRESCRIPTION_KEY, prescriptions); }, [prescriptions]);
  useEffect(() => { void idbSet(BATCH_KEY, batches); }, [batches]);
  useEffect(() => () => { zxingControlsRef.current?.stop(); streamRef.current?.getTracks().forEach((t) => t.stop()); }, []);

  const value = cleanLabel(detected || manual);
  const current = useMemo(() => findScript(scripts, value), [scripts, value]);
  const matchedLabels = useMemo(() => scans.filter((s) => s.record?.scriptNumber && prescriptions.some((p) => p.scriptNumber === s.record?.scriptNumber && medLooksSame(p.medicine, s.record?.medicine))), [scans, prescriptions]);
  const unmatchedLabels = useMemo(() => scans.filter((s) => !s.record?.scriptNumber || !prescriptions.some((p) => p.scriptNumber === s.record?.scriptNumber && medLooksSame(p.medicine, s.record?.medicine))), [scans, prescriptions]);
  const unmatchedPrescriptions = useMemo(() => prescriptions.filter((p) => !p.scriptNumber || !scans.some((s) => s.record?.scriptNumber === p.scriptNumber && medLooksSame(p.medicine, s.record?.medicine))), [prescriptions, scans]);
  const masterRange = rangeLabel(scripts);
  const preview: Scan | null = value ? { value, savedAt: new Date().toISOString(), status: current ? "matched" : "unmatched", record: current } : last;
  const rxSuggestions = useMemo(() => { const p = norm(rxManual.patient), m = norm(rxManual.medicine), mc = dig(rxManual.medicare), dt = dig(rxManual.date); if (!p && !m && !mc && !dt) return []; return scripts.filter((script) => (!p || norm(script.patient).includes(p)) && (!m || norm(script.medicine).includes(m)) && (!mc || dig(script.medicare).includes(mc)) && (!dt || dig(auDate(script.dispenseDate)).includes(dt) || dig(script.dispenseDate).includes(dt))).slice(0, 12); }, [scripts, rxManual]);

  const tableRows = useMemo<ReviewRow[]>(() => {
    if (tableMode === "matched") return matchedLabels.map((scan) => { const rx = prescriptions.find((p) => p.scriptNumber === scan.record?.scriptNumber && medLooksSame(p.medicine, scan.record?.medicine)); return { Status: "MATCHED", Label: scan.value, Script: scan.record?.scriptNumber || "", Patient: scan.record?.patient || rx?.patient || "", Address: rx?.address || "", Date: auDate(scan.record?.dispenseDate || rx?.date || ""), Medicine: scan.record?.medicine || rx?.medicine || "", LabelTime: fmt(scan.savedAt), PrescriptionTime: rx ? fmt(rx.savedAt) : "" }; });
    if (tableMode === "unmatchedLabels") return unmatchedLabels.map((scan) => ({ Status: "UNMATCHED_LABEL", Label: scan.value, Script: scan.record?.scriptNumber || "", Patient: scan.record?.patient || "", Address: "", Date: auDate(scan.record?.dispenseDate || ""), Medicine: scan.record?.medicine || "", LabelTime: fmt(scan.savedAt), PrescriptionTime: "" }));
    return unmatchedPrescriptions.map((rx) => ({ Status: "UNMATCHED_PRESCRIPTION", Label: "", Script: rx.scriptNumber || "", Patient: rx.patient, Address: rx.address || "", Date: rx.date, Medicine: rx.medicine, LabelTime: "", PrescriptionTime: fmt(rx.savedAt) }));
  }, [tableMode, matchedLabels, unmatchedLabels, unmatchedPrescriptions, prescriptions]);

  const recentItems = useMemo<RecentItem[]>(() => { const labelItems = scans.map((s) => ({ kind: "Label" as const, title: s.value, subtitle: s.record ? `${s.record.patient || "-"} | ${s.record.medicine || "-"}` : "No FRED match yet", time: s.savedAt })); const rxItems = prescriptions.map((p) => ({ kind: "Prescription" as const, title: p.scriptNumber || p.patient || "Prescription saved", subtitle: `${p.patient || "-"} | ${p.medicine || "-"}${p.address ? ` | address saved separately` : ""}`, time: p.savedAt })); return [...labelItems, ...rxItems].sort((a, b) => new Date(b.time).getTime() - new Date(a.time).getTime()).slice(0, 3); }, [scans, prescriptions]);

  async function upload(file: File) { setUploadState({ active: true, percent: 5, label: `Selected ${file.name}` }); await sleep(40); try { setUploadState({ active: true, percent: 25, label: "Reading FRED Excel..." }); const incoming = await parseFredFile(file); if (incoming.length === 0) { setUploadState({ active: false, percent: 0, label: "" }); notify("No script rows found in FRED export."); return; } const map = new Map(scripts.map((r) => [r.scriptNumber, r])); let updated = 0; for (const rec of incoming) { if (!rec.scriptNumber) continue; if (map.has(rec.scriptNumber)) updated += 1; map.set(rec.scriptNumber, rec); } const merged = [...map.values()].sort((a, b) => dateValue(a.dispenseDate) - dateValue(b.dispenseDate)); const fileRange = rangeLabel(incoming); const batch = { fileName: file.name, uploadedAt: new Date().toISOString(), from: fileRange.from, to: fileRange.to, imported: incoming.length, updated, total: merged.length }; setUploadState({ active: true, percent: 90, label: "Saving master..." }); await idbSet(SCRIPT_KEY, merged); await idbSet(BATCH_KEY, [batch, ...batches]); setScripts(merged); setBatches((old) => [batch, ...old]); notify(`FRED uploaded: ${fileRange.from || "?"} to ${fileRange.to || "?"}. Total ${merged.length}.`); setUploadState({ active: true, percent: 100, label: `Uploaded. Master total ${merged.length}.` }); window.setTimeout(() => setUploadState({ active: false, percent: 0, label: "" }), 1600); } catch (e) { setUploadState({ active: false, percent: 0, label: "" }); notify(e instanceof Error ? `Upload failed: ${e.message}` : "Upload failed."); } }
  async function startScanner() { if (!videoRef.current) return; stopScanner(); try { const [{ BrowserMultiFormatReader }, { BarcodeFormat, DecodeHintType }] = await Promise.all([import("@zxing/browser"), import("@zxing/library")]); const hints = new Map(); hints.set(DecodeHintType.POSSIBLE_FORMATS, [BarcodeFormat.CODE_128, BarcodeFormat.CODE_39, BarcodeFormat.CODE_93, BarcodeFormat.EAN_13, BarcodeFormat.EAN_8, BarcodeFormat.ITF, BarcodeFormat.QR_CODE]); const reader = new BrowserMultiFormatReader(hints); const controls = await reader.decodeFromVideoDevice(undefined, videoRef.current, (result) => { const raw = result?.getText?.()?.trim(); const val = cleanLabel(raw); if (val) { setDetected((old) => { if (old !== val) setMessage(raw !== val ? `Label detected and cleaned: ${raw} → ${val}` : `Label detected: ${val}`); return val; }); setManual(""); } }); zxingControlsRef.current = controls; setCameraOn(true); setMessage("Scanner ready. Use one Save button: barcode saves label; no barcode scans prescription with AI."); } catch { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" }, width: { ideal: 1920 }, height: { ideal: 1080 } }, audio: false }); streamRef.current = stream; videoRef.current.srcObject = stream; setCameraOn(true); setMessage("Camera opened, but barcode decoder failed. You can still use Save current scan for prescription AI or manual label."); } catch { notify("Camera permission denied or no camera found."); } } }
  function stopScanner() { zxingControlsRef.current?.stop(); zxingControlsRef.current = null; streamRef.current?.getTracks().forEach((t) => t.stop()); streamRef.current = null; setCameraOn(false); }
  function saveLabel() { const v = cleanLabel(value); if (!v) return false; const rec = findScript(scripts, v); const already = scans.some((s) => norm(s.value) === norm(v)); const scan: Scan = { value: v, savedAt: new Date().toISOString(), status: rec ? "matched" : "unmatched", record: rec }; setScans((old) => [scan, ...old.filter((s) => norm(s.value) !== norm(v))]); setLast(scan); setManual(""); setDetected(""); notify(already ? `Duplicate label updated: ${v}` : rec ? `Label saved: ${v} | ${rec.patient || "patient found"} | ${rec.medicine || "medicine"}` : `Label saved as unmatched: ${v}`); return true; }
  function prescriptionKey(entry: Omit<PrescriptionEntry, "id" | "savedAt"> | PrescriptionEntry) { return entry.scriptNumber ? `script:${entry.scriptNumber}:${norm(entry.medicine)}` : `free:${norm(entry.patient)}:${dig(entry.date)}:${norm(entry.medicine)}:${dig(entry.medicare)}`; }
  function savePrescriptionEntries(entries: Omit<PrescriptionEntry, "id" | "savedAt">[]) { if (entries.length === 0) { notify("AI could not read a medicine item. Try closer/clearer scan."); return; } let duplicateCount = 0; const next = entries.map((entry) => ({ ...entry, id: id(), savedAt: new Date().toISOString() })); setPrescriptions((old) => { const incomingKeys = new Set(next.map(prescriptionKey)); duplicateCount = old.filter((p) => incomingKeys.has(prescriptionKey(p))).length; return [...next, ...old.filter((p) => !incomingKeys.has(prescriptionKey(p)))]; }); notify(`${next.length} prescription item${next.length > 1 ? "s" : ""} saved separately${duplicateCount ? ` (${duplicateCount} duplicate updated)` : ""}.`); }
  function savePrescriptionEntry(entry: Omit<PrescriptionEntry, "id" | "savedAt">) { savePrescriptionEntries([entry]); }
  async function scanPrescriptionWithAi() { if (!videoRef.current || !cameraOn) { notify("Start scanner first."); return; } setScannerBusy(true); setMessage("AI is reading this prescription now. For handwriting, hold steady and close..."); try { const video = videoRef.current; const canvas = document.createElement("canvas"); canvas.width = Math.min(video.videoWidth || 1280, 1600); canvas.height = Math.round(canvas.width * ((video.videoHeight || 720) / (video.videoWidth || 1280))); const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("Cannot capture scanner frame"); ctx.drawImage(video, 0, 0, canvas.width, canvas.height); const image = canvas.toDataURL("image/jpeg", 0.78); const response = await fetch("/api/ai-detect-prescription", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image }) }); const data = await response.json(); if (!data.ok) throw new Error(data.error || "AI detection failed"); const r = data.result || {}; const patientRaw = String(r.patient || "").trim(); const patient = isLikelyAddress(patientRaw) ? "" : patientRaw; const address = String(r.address || (isLikelyAddress(patientRaw) ? patientRaw : "")).trim(); const meds: AiMedicine[] = Array.isArray(r.medicines) && r.medicines.length ? r.medicines : (r.medicine ? [{ medicine: r.medicine }] : []); const baseScript = cleanLabel(r.scriptNumber); const entries = meds.map((med, index) => { const labelNo = cleanLabel(med.labelNumber); const cleanScript = labelNo || baseScript; const rec = cleanScript ? findScript(scripts, cleanScript) : undefined; return { source: "scanner" as const, scriptNumber: rec?.scriptNumber || cleanScript || undefined, patient: rec?.patient || patient, address, date: auDate(rec?.dispenseDate || r.date || ""), medicine: rec?.medicine || String(med.medicine || ""), medicare: rec?.medicare || r.medicare || "", quantity: med.quantity || "", repeats: med.repeats || "", directions: med.directions || "", itemIndex: index + 1 }; }).filter((e) => e.medicine || e.scriptNumber || e.patient); if (entries[0]) setRxManual({ patient: entries[0].patient, date: entries[0].date, medicine: entries[0].medicine, medicare: entries[0].medicare }); savePrescriptionEntries(entries); } catch (e) { notify(e instanceof Error ? `AI prescription scan failed: ${e.message}` : "AI prescription scan failed."); } finally { setScannerBusy(false); } }
  function saveCurrentScan() { if (value.trim()) { saveLabel(); return; } void scanPrescriptionWithAi(); }
  function saveManualPrescription() { savePrescriptionEntry({ source: "manual", patient: rxManual.patient.trim(), address: "", date: rxManual.date.trim(), medicine: rxManual.medicine.trim(), medicare: rxManual.medicare.trim() }); }
  function selectPrescription(script: ScriptRec) { const entry = { source: "fred-search" as const, scriptNumber: script.scriptNumber, patient: script.patient, address: "", date: auDate(script.dispenseDate), medicine: script.medicine, medicare: script.medicare || "" }; setRxManual({ patient: entry.patient, date: entry.date, medicine: entry.medicine, medicare: entry.medicare }); savePrescriptionEntry(entry); }
  function clearScans() { setScans([]); setLast(null); void idbDel(SCAN_KEY); notify("Label scans cleared."); }
  function clearPrescriptions() { setPrescriptions([]); void idbDel(PRESCRIPTION_KEY); notify("Prescriptions cleared."); }
  function clearMaster() { setScripts([]); setBatches([]); void idbDel(SCRIPT_KEY); void idbDel(BATCH_KEY); notify("FRED master cleared."); }

  return <main className="min-h-screen bg-slate-950 px-4 py-4 text-slate-100 sm:px-6 lg:px-8"><section className="mx-auto flex max-w-7xl flex-col gap-4">
    {toast && <div className="fixed inset-x-4 top-5 z-50 mx-auto max-w-xl rounded-3xl bg-emerald-600 px-5 py-4 text-center text-lg font-black text-white shadow-2xl ring-4 ring-emerald-200">✓ {toast}</div>}
    <header className="rounded-3xl border border-white/10 bg-white/10 p-5 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[0.3em] text-emerald-300">Pharmacy Verification</p><h1 className="mt-2 text-2xl font-black text-white sm:text-4xl">Single live scanner</h1><p className="mt-3 text-sm leading-7 text-slate-300">{scripts.length ? `Scripts from ${masterRange.from} to ${masterRange.to}` : "Upload FRED file at the bottom."}</p><p className="mt-2 rounded-2xl bg-white/10 p-3 text-sm font-bold text-slate-200">{message}</p></header>
    <section className="grid gap-3 sm:grid-cols-4"><button onClick={() => setTableMode("unmatchedLabels")} className="rounded-2xl bg-white p-4 text-left text-slate-950"><p className="text-2xl font-black">{scans.length}</p><p className="text-xs text-slate-500">Saved labels</p></button><button onClick={() => setTableMode("matched")} className="rounded-2xl bg-emerald-100 p-4 text-left text-emerald-950"><p className="text-2xl font-black">{matchedLabels.length}</p><p className="text-xs">Matched pairs</p></button><button onClick={() => setTableMode("unmatchedLabels")} className="rounded-2xl bg-amber-100 p-4 text-left text-amber-950"><p className="text-2xl font-black">{unmatchedLabels.length + unmatchedPrescriptions.length}</p><p className="text-xs">Unmatched work items</p></button><button onClick={() => setTableMode("unmatchedPrescriptions")} className="rounded-2xl bg-white/10 p-4 text-left text-white"><p className="text-2xl font-black">{prescriptions.length}</p><p className="text-xs text-slate-400">Saved prescription items</p></button></section>
    <section className="rounded-3xl bg-white p-4 text-slate-950 shadow-xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">{tableMode === "matched" ? "Matched pairs" : tableMode === "unmatchedLabels" ? "Unmatched labels" : "Unmatched prescription items"}</h2><p className="text-sm text-slate-500">Address is kept separate. Multi-item prescriptions create one row per medicine.</p></div><button onClick={() => downloadCsv(`${tableMode}-pharmacy-verification.csv`, tableRows)} disabled={tableRows.length === 0} className="rounded-full bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Export CSV</button></div><div className="mt-4 max-h-72 overflow-auto rounded-2xl border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="sticky top-0 bg-slate-100"><tr>{["Status", "Label", "Script", "Patient", "Address", "Date", "Medicine", "LabelTime", "PrescriptionTime"].map((h) => <th key={h} className="p-3 font-black">{h}</th>)}</tr></thead><tbody>{tableRows.length === 0 ? <tr><td colSpan={9} className="p-5 text-center text-slate-500">No rows yet.</td></tr> : tableRows.map((row, index) => <tr key={index} className="border-t"><td className="p-3 font-black">{row.Status}</td><td className="p-3">{row.Label}</td><td className="p-3">{row.Script}</td><td className="p-3">{row.Patient}</td><td className="p-3">{row.Address}</td><td className="p-3">{row.Date}</td><td className="p-3">{row.Medicine}</td><td className="p-3">{row.LabelTime}</td><td className="p-3">{row.PrescriptionTime}</td></tr>)}</tbody></table></div></section>
    <section className={`rounded-3xl bg-gradient-to-br from-emerald-50 to-white p-4 text-slate-950 shadow-xl ring-2 transition-all duration-300 ${flash ? "ring-emerald-500 shadow-emerald-300/60" : "ring-emerald-200"}`}><h2 className="mb-3 text-xl font-black">Live scanner</h2><div className="grid gap-4 lg:grid-cols-[320px_1fr]"><div><div className={`relative overflow-hidden rounded-3xl border-2 bg-slate-100 shadow-inner transition-all ${flash ? "border-emerald-500" : "border-emerald-300"}`}><video ref={videoRef} className="h-52 w-full object-cover" autoPlay muted playsInline /><div className="pointer-events-none absolute inset-x-10 top-1/2 h-16 -translate-y-1/2 rounded-2xl border-4 border-white/80 shadow-[0_0_0_9999px_rgba(15,23,42,0.10)]" /></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={startScanner} className="rounded-2xl bg-emerald-600 px-4 py-3 font-black text-white shadow-sm">Start</button><button onClick={stopScanner} className="rounded-2xl border bg-white px-4 py-3 font-bold shadow-sm">Stop</button></div></div><div className="flex flex-col gap-3"><div className="rounded-3xl bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Detected label / script number</p><p className="mt-2 min-h-10 break-all text-3xl font-black">{value || "No barcode detected"}</p></div><button onClick={saveCurrentScan} disabled={scannerBusy || (!cameraOn && !value.trim())} className="rounded-3xl bg-slate-950 px-6 py-5 text-xl font-black text-white shadow-sm disabled:opacity-40">{scannerBusy ? "Saving..." : value ? "Save current label" : "Save current scan"}</button>{preview?.record && <div className="rounded-3xl bg-white p-4 text-sm shadow-sm"><p className="font-black text-emerald-800">FRED lookup found</p><p><strong>Patient:</strong> {preview.record.patient}</p><p><strong>Date:</strong> {auDate(preview.record.dispenseDate)}</p><p><strong>Medicine:</strong> {preview.record.medicine}</p><p><strong>Script:</strong> {preview.record.scriptNumber}</p></div>}</div></div></section>
    <section className="rounded-3xl bg-white p-4 text-slate-950 shadow-xl"><h2 className="text-lg font-black">Last 3 saved items</h2><div className="mt-3 grid gap-2">{recentItems.length === 0 ? <p className="rounded-2xl bg-slate-100 p-4 text-sm font-bold text-slate-500">Nothing saved yet.</p> : recentItems.map((item) => <div key={`${item.kind}-${item.time}-${item.title}`} className="rounded-2xl border p-3"><div className="flex items-center justify-between gap-2"><strong>{item.kind}: {item.title}</strong><span className="text-xs text-slate-500">{fmt(item.time)}</span></div><p className="mt-1 text-sm text-slate-600">{item.subtitle}</p></div>)}</div></section>
    <details className="rounded-3xl bg-white p-4 text-slate-950 shadow-xl"><summary className="cursor-pointer text-lg font-black">Manual label fallback</summary><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><input value={manual} onChange={(e) => { setManual(cleanLabel(e.target.value)); setDetected(""); }} onKeyDown={(e) => { if (e.key === "Enter") saveLabel(); }} placeholder="Type script / label number manually" className="rounded-2xl border-2 px-4 py-4 text-xl font-black" /><button onClick={saveLabel} disabled={!value.trim()} className="rounded-2xl bg-slate-950 px-6 py-4 font-black text-white disabled:opacity-40">Save label</button></div></details>
    <details className="rounded-3xl bg-white p-4 text-slate-950 shadow-xl"><summary className="cursor-pointer text-lg font-black">Manual prescription / live search</summary><div className="relative mt-4 grid gap-3 sm:grid-cols-4"><input value={rxManual.patient} onChange={(e) => setRxManual({ ...rxManual, patient: e.target.value })} placeholder="Patient name" className="rounded-2xl border-2 px-4 py-3 font-bold" /><input value={rxManual.date} onChange={(e) => setRxManual({ ...rxManual, date: e.target.value })} placeholder="Prescription date" className="rounded-2xl border-2 px-4 py-3 font-bold" /><input value={rxManual.medicine} onChange={(e) => setRxManual({ ...rxManual, medicine: e.target.value })} placeholder="Medicine" className="rounded-2xl border-2 px-4 py-3 font-bold" /><input value={rxManual.medicare} onChange={(e) => setRxManual({ ...rxManual, medicare: e.target.value })} placeholder="Medicare number" className="rounded-2xl border-2 px-4 py-3 font-bold" /></div><button onClick={saveManualPrescription} disabled={!rxManual.patient && !rxManual.medicine && !rxManual.medicare} className="mt-3 rounded-2xl bg-slate-950 px-5 py-3 font-black text-white disabled:opacity-40">Save prescription item</button>{rxSuggestions.length > 0 && <div className="mt-3 max-h-80 overflow-auto rounded-3xl border bg-white p-3 shadow-xl"><p className="mb-2 text-sm font-black text-slate-600">Live FRED candidates</p>{rxSuggestions.map((script) => <button key={script.scriptNumber} onClick={() => selectPrescription(script)} className="mb-2 block w-full rounded-2xl border p-3 text-left hover:bg-emerald-50"><div className="flex flex-wrap items-center justify-between gap-2"><strong>Script {script.scriptNumber}</strong><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{auDate(script.dispenseDate)}</span></div><p className="mt-1 text-sm"><strong>{script.patient}</strong> | {script.medicine}</p></button>)}</div>}</details>
    <footer className="rounded-3xl bg-white/10 p-4 text-center"><input type="file" accept=".xlsx,.xls,.csv,.tsv,.txt" disabled={uploadState.active} onChange={(e) => { const f = e.target.files?.[0]; if (f) void upload(f); e.currentTarget.value = ""; }} className="block w-full rounded-2xl bg-white p-4 text-sm font-black text-slate-950 file:mr-4 file:rounded-full file:border-0 file:bg-emerald-600 file:px-5 file:py-3 file:font-black file:text-white disabled:opacity-50" />{uploadState.active && <div className="mt-4 rounded-2xl bg-white p-4 text-left text-slate-950"><div className="flex items-center justify-between text-sm font-black"><span>{uploadState.label}</span><span>{uploadState.percent}%</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-600 transition-all" style={{ width: `${uploadState.percent}%` }} /></div></div>}{batches.length > 0 && <p className="mt-3 text-sm text-slate-300">Last upload: Scripts from {batches[0].from} to {batches[0].to} uploaded. Master total: {batches[0].total}</p>}<div className="mt-3 flex justify-center gap-3">{batches.length > 0 && <button onClick={clearMaster} className="text-xs font-bold text-rose-300">Clear FRED master</button>}<button onClick={clearScans} className="text-xs font-bold text-rose-300">Clear labels</button><button onClick={clearPrescriptions} className="text-xs font-bold text-rose-300">Clear prescriptions</button></div></footer>
  </section></main>;
}
